### ISSUE TITLE
Try to upgrade bootloader to 0.10.6, but failed to boot

### ISSUE THREAD

**Issue by i11010520** [vinc/moros#229]
I tried to upgrade bootloader 0.9.18 + bootimage to the newer bootloader 0.10.6, the implementation like following diffs:
[diff.log](https://github.com/vinc/moros/files/6948553/diff.log)

`cargo krun` hang at the entry point of Jumping to kernel:
<img width="644" alt="截屏2021-08-07 上午11 01 14" src="https://user-images.githubusercontent.com/86607589/128586978-742e0a43-528f-41fe-aa64-6336467dd716.png">

Are you interested in handling this issue?

**Comment by vinc** [comment]
Hi, it's pretty cool that you are experimenting with MOROS! :+1: 

I'm a bit undecided at the moment regarding the 0.10 version of the bootloader crate. Adding UEFI means dropping support of VGA text mode, which I can see being done in the future because it means more text can fit in the screen and MOROS will be able to run on newer computers that have UEFI without CSM, but at the moment I like the simplicity of this mode.

I think on a personal level when developing MOROS I want to fully understand the BIOS era before moving to the UEFI era. So I think I won't upgrade for now, but will most probably in the future.

**Comment by i11010520** [comment]
Is it possible to bring some GUI library to MOROS,  like LVGL, sixtyfpx, etc?
How far is it?

**Comment by vinc** [comment]
Short answer: not far along at all I'm afraid :(

As a programmer can allocate memory, you can get chars from the keyboard and send them to the screen or the serial interface, you can read and write blocks on the disk, or manipulate files and directories, you can send and receive packets on the network, read the clock, generate a random number, mostly very basic stuff.

As a user you can interact with the system on a shell, use a text editor, a lisp interpreter, and soon play a game of chess.

But everything is very limited with lots and lots of caveats! There's no libc, no multitasking, and the userspace is not even real yet, everything run inside the kernel ^^

I think it'd take a lifetime to implement alone a full operating system, and that's great because programming MOROS is a hobby that should provide me lots of fun for a very long time. My hope is that by being open source it will help people doing the same, like the awesome open source projects that are helping me understanding OS development.

As it is today it's not a good base to build something substantial on top of it, it's too limited and unstable. I'd say it's only good if you want to experiment with a specific part of a kernel without writing your own kernel.
