### ISSUE TITLE
UEFI Support

### ISSUE THREAD

**Issue by ghost** [vinc/moros#270]
Will it be possible to run the system on uefi in the future?

**Comment by vinc** [comment]
Hello, as I wrote [here](https://github.com/vinc/moros/issues/229) I'm not sure about UEFI at the moment because I like the simplicity of VGA Text Mode with the BIOS. It would make sens to support it, along with other modern features like AHCI (SATA) and USB, but it'll increase the complexity of the project.

**Comment by ghost** [comment]
If it ever gets decided that UEFI gets implemented, I have worked with UEFI on my own OS in rust before and I might be able to provide help :+1:
